# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Required by RNFirebase
pod 'Firebase/Core'

target 'cryptomon' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cryptomon

  target 'cryptomon-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cryptomonTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
